### ISSUE TITLE
gzipped input?

### ISSUE THREAD

**Issue by ctb** [COMBINE-lab/cuttlefish#11]
hi, thanks for releasing 2.0! I successfully installed and ran it on Mac OS X 🎉 (and presumably Linux will just work :).

Our workflows generally produce gzipped FASTQ files after preprocessing. It seems like cuttlefish does not currently support them; thought I'd drop this issue here to check in and let you know that we'd love that support :).

**Comment by jamshed** [comment]
Hello Titus,

Cuttlefish do support gzipped inputs! Could you please paste here what commands are you trying to use for cuttlefish, and what error messages are you getting?

**Comment by ctb** [comment]
excellent! I double-checked and (of course) you're right. I think I was trying on a gzipped FASTA file rather than a FQ file at first, and I never went back and checked with a proper FQ file. Thanks!
