### ISSUE TITLE
exception when trying to use the software

### ISSUE THREAD

**Issue by PandorasRed** [COMBINE-lab/cuttlefish#18]
hello,

i have this exception when i try to execute cuttlefish:
terminate called after throwing an instance of 'CThreadCancellationException'

the command i use is : cuttlefish build -l list-meta -o metacuttle  -k 31 --ref -m 1024 -t 32

**Comment by jamshed** [comment]
HI @PandorasRed:

Thanks for using Cuttlefish! What's the type of the input files that you're trying to use here, i.e. are these FASTQ or FASTA?

**Comment by PandorasRed** [comment]
its Fastq, didn't check and i was thinking i was working with fasta file, i have changed the ref to read and add the cutoff option for my test and it seems to run correctly now, thank for pointing it

**Comment by jamshed** [comment]
Hi @PandorasRed, thanks for letting us know!
