### ISSUE TITLE
gfa visualization

### ISSUE THREAD

**Issue by EA2106-Universite-Francois-Rabelais** [COMBINE-lab/cuttlefish#2]
Hi!
I successfully ran cuttlefish on 3 plant genomes (indeed in a very fast way). I would like to visualize the resulting pan-genome (could it be really named like this in this case?) from the gfa file (either gfa1 or gfa2). I tried SGTK (https://github.com/olga24912/SGTK) but without success. I will also try other https://github.com/rrwick/Bandage and https://github.com/ggonnella/gfaviz, but I wondered if you already have experience in this kind of task before going through it.
Thanks and congrats for this impressive work.

**Comment by jamshed-k** [comment]
Hi!

Glad that you found Cuttlefish useful! We haven't yet tried visualizing the GFA outputs, but we intend to. We are a bit busy with the final draft of the paper right now, but we will get back to you shortly, hopefully within a few days. Let us know if you could sort out the stuff in the mean time, and / or need any other assistance using Cuttlefish!

Thanks!

**Comment by EA2106-Universite-Francois-Rabelais** [comment]
Hi Jamshed,
ok I will perform several tests and keep you updated!
Good luck  with the writing.

**Comment by jamshed-k** [comment]
Hi @EA2106-Universite-Francois-Rabelais,

I've been able to visualize the GFA1 output using [Bandage](https://github.com/rrwick/Bandage)!

**Comment by EA2106-Universite-Francois-Rabelais** [comment]
Dear @jamshed-k 
thanks for the update! I am working with quite a large file and I have to download it from my computing grid. I will give a try!

**Comment by EA2106-Universite-Francois-Rabelais** [comment]
I indeed tried bandage with a toy example adaptated from my own datasets (with some variations added manually). Worked perfectly with gfa1 format but not gfa2 (seems to be unable to detect edges with this version).

![graph](https://user-images.githubusercontent.com/17110750/98957442-7dc21b00-2501-11eb-93c2-99d24393fb1a.png)

**Comment by jamshed-k** [comment]
Hi @EA2106-Universite-Francois-Rabelais,

Indeed, the visualizations are good for small enough graphs. For example, the following two are for the compacted de Bruijn graph of the _E. Coli_ genome:

**_k_ = 101**:
![ecoli-k101](https://user-images.githubusercontent.com/44490895/99342293-93b14200-2859-11eb-88c3-0a096b08cf39.png)

**_k_ = 255**:
![ecoli-k255](https://user-images.githubusercontent.com/44490895/99342466-e854bd00-2859-11eb-8852-d2ba1d1fe484.png)

I'm closing the issue for now. Please let us know if you do experiment more and find other suitable alternatives!
