### ISSUE TITLE
docker image?

### ISSUE THREAD

**Issue by shenweima** [COMBINE-lab/cuttlefish#20]
I failed to install it by conda, so could you offer us a docker image?

**Comment by rob-p** [comment]
Hi @shenweima,

  You should be able to pull from the docker registry that is populated via bioconda as follows:

```
docker pull quay.io/biocontainers/cuttlefish:2.1.0--hf1761c0_0
```

Please let us know if this works for you.

Best,
Rob

**Comment by shenweima** [comment]
Thanks , work
