### ISSUE TITLE
tools for the result of cuttlefish?

### ISSUE THREAD

**Issue by shenweima** [COMBINE-lab/cuttlefish#21]
I want to use cuttlefish to my WGS popupation including 500 accessions. When get ucontigs for all accessions, I am not very clear to how to do next step analysis, Can you give me some advice or some related papers?

**Comment by jamshed** [comment]
Hello @shenweima,

Thank you for using cuttlefish! Could you please detail your use-cases a bit more? That way, we might be able to help you better.

Regards.
