### ISSUE TITLE
Using Cuttlefish2 with Corrected Long Reads

### ISSUE THREAD

**Issue by jwalewski** [COMBINE-lab/cuttlefish#23]
Hello,

I am interested in using Cuttlefish 2 in the genome research I am doing - I know this falls outside the primary scope of Cuttlefish, but I would like to use it at the end of a hybrid genome assembly pipeline (to assemble long reads corrected by short reads via FMLRC2).

However, FMLRC2 outputs reads with a .fa file format, and I am trying to do de novo hybrid genome assembly, and I understand that cuttlefish2 can only work with FASTQ files, so I wrote a program to convert the FASTA reads back into FASTQ format.

Luckily, Cuttlefish2 does indeed read the file and enumerates edges, but then, regardless of kmer size, I keep getting this warning:
"""Warning: using counter_max == 1 will cause not storying counters in KMC output file, all counters will be assumed to be 1. This is experimental and is not currently supported in kmc_tools. Will be implemented soon.""""

Then, this goes on and "ruins" the rest of the process. Here's everything:

"""
Constructing the compacted read de Bruijn graph for k = 27.

Enumerating the edges of the de Bruijn graph.
***************************************************************************************************************************************************************************************************************************************************************************************************************************
Stage 1: 100%
Warning: using counter_max == 1 will cause not storying counters in KMC output file, all counters will be assumed to be 1. This is experimental and is not currently supported in kmc_tools. Will be implemented soon.
Stage 2: 100%

28-mer enumeration statistics:
        Number of sequences:    31448.
        Total sequence length:  849096.
        Total number of 28-mers:        0.
        Number of unique 28-mers:       0.
        Number of solid 28-mers:        0.
Enumerated the edge set of the graph. Time taken = 441.307 seconds.

Enumerating the vertices of the de Bruijn graph.
Stage 1: 100%
Warning: using counter_max == 1 will cause not storying counters in KMC output file, all counters will be assumed to be 1. This is experimental and is not currently supported in kmc_tools. Will be implemented soon.
Stage 2: 100%

Enumerated the vertex set of the graph. Time taken = 6.03567 seconds.
Number of edges:    0.
Number of vertices: 0.

Constructing the minimal perfect hash function (MPHF) over the vertex set.
Total number of k-mers in the set (KMC database): 0.
Building the MPHF from the k-mer database /mnt/f/ultimate/Silico_data/Cuttlefish_work_dir/TEST_12.9.22.cf_V.
Using gamma = 10.
Built the MPHF in memory.

Total MPHF size: 0 MB. Bits per k-mer: -nan.
Allocated hash table buckets for the k-mers. Total size: 0 MB.
Total memory usage by the hash table: 0 MB. Bits per k-mer: -nan.
Constructed the minimal perfect hash function for the vertices. Time taken = 0.0029513 seconds.

Computing the DFA states.
Total number of distinct edges: 0.

Number of processed edges: 0

Completed a pass over the k-mer database.
Computed the states of the automata. Time taken = 0.0176653 seconds.

Extracting the maximal unitigs.
Number of distinct vertices: 0.

Number of scanned vertices: 0.
Number of maximal unitigs: 0.
Number of k-mers in the maximal unitigs: 0.
Length of the longest maximal unitig (in bases):  0.
Length of the shortest maximal unitig (in bases): 18446744073709551615.
Sum length of the maximal unitigs (in bases): 0.
Extracted the paths. Time taken = 0.0120092 seconds.

Completed a pass over the k-mer database.
Extracted the paths. Time taken = 0.0148171 seconds.

Maximum temporary disk-usage: 0.0360186GB.

Structural information for the de Bruijn graph is written to /mnt/f/ultimate/silico_data/assembly_output/CUTTLEFISH/TEST_12.9.22.json.

Constructed the read compacted de Bruijn graph at /mnt/f/ultimate/silico_data/assembly_output/CUTTLEFISH/TEST_12.9.22.
"""

This doesn't happen with "normal" FASTQ files, so let me know if I need to modify my program!

**Comment by jamshed** [comment]
Hi @jwalewski:

Actually, Cuttlefish 2 can work with both FASTQ and FASTA files! If you already have FASTA files, and do not want to filter any _k_-mers, then you could just use the `--ref` option instead of `--read` with Cuttlefish 2—although you're working with reads, since you do not want filtering on the input FASTA files, these can be _viewed_ as reference sequences from the PoV of the tool. Let me know if this works for you!

That being said, I wonder why it reports zero 28-mers on the (converted) FASTQ files you're using (in your log). I'm interested to look into your converted code, if it's possible for you to post it somewhere.

Regards.

**Comment by jwalewski** [comment]
Hello again,

Using the --ref parameter on FMLRC2's FASTA reads worked, thanks so much!
