### ISSUE TITLE
Multiple different crashes (CThreadCancellationException and Cannot open temporary file)

### ISSUE THREAD

**Issue by rlorigro** [COMBINE-lab/cuttlefish#29]
Hi,

I followed the instructions to build cuttlefish from source, but when I run it on a small FASTA file:
```
cuttlefish build -k 31 -t 32 --ref -s ../n4.fasta -o test_cuttlefish
```
I get this output:
```

Constructing the compacted reference de Bruijn graph for k = 31.

Enumerating the edges of the de Bruijn graph.
**

Structural information for the de Bruijn graph is written to test_cuttlefish.json.
Error: Cannot open temporary file ./kmc_01021.bin

Usage :
Efficiently construct the compacted de Bruijn graph from sequencing reads or reference sequences
Usage:
  cuttlefish build [OPTION...]
```

Alternatively, when i run it with the `--read` option:
```
cuttlefish build -k 31 -t 32 --read -s ../n4.fasta -o test_cuttlefish2
```

I get this output:
```
Constructing the compacted read de Bruijn graph for k = 31.

Enumerating the edges of the de Bruijn graph.

terminate called after throwing an instance of 'CThreadCancellationException'
Aborted (core dumped)
```

**Comment by rickbeeloo** [comment]
I have had the first one ("`Cannot open temporary file ./kmc_01021.bin`") and solved that with the `ulimit -n 2048` mentioned [here](https://github.com/COMBINE-lab/cuttlefish/issues/12#issuecomment-1116149220)

**Comment by rlorigro** [comment]
Ah thanks for the v quick answer. That's working now. It hasn't fixed the CThreadCanellationException though, unfortunately

**Comment by rob-p** [comment]
This is, seemingly, KMC related.  Out of curiosity, can you run KMC to just _count_ the k-mers on this same dataset?

**Comment by rlorigro** [comment]
Using the binary produced during compilation of cuttlefish i get this result:
```
kmc -k31 -t32 ../n4.fasta test_kmc .

Error: unknown exception
```

same error if I don't use any thread/k argument

**Comment by rob-p** [comment]
Well, I think you have to tell `kmc` that you're providing a multi-line FASTA file.

```
kmc -k31 -fm -t32 ../n4.fasta test_kmc 
```

I'd be interested if you get the same thing from the official KMC release. We track that pretty closely and, if so, this seems like something we should report upstream.

**Comment by rlorigro** [comment]
Works now :+1: 
```
kmc -k31 -fm -t32 ../n4.fasta test_kmc .
**
Stage 1: 100%
Stage 2: 100%
1st stage: 0.143339s
2nd stage: 1.18693s
Total    : 1.33027s
Tmp size : 1MB

Stats:
   No. of k-mers below min. threshold :       114266
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :       195746
   No. of unique counted k-mers       :        81480
   Total no. of k-mers                :      1791965
   Total no. of sequences             :           86
   Total no. of super-k-mers          :       146315
```

**Comment by rlorigro** [comment]
Compiling the main branch from KMC has the exact same behavior

**Comment by rob-p** [comment]
Tagging @jamshed here. Any idea why we'd see an exception related to a KMC type in cuttlefish but not under KMC itself?

**Comment by jamshed** [comment]
Hi @rlorigro: this exception is raised from the KMC input-type argument, which can have three values: `-fa`, `-fm`, and `-fq`. Since in the following command you used `--read`, cuttlefish assumes that FASTQ input is provided—it sets `-fq` for KMC, which then exits since FASTA is provided whereas it expects otherwise.
> cuttlefish build -k 31 -t 32 --read -s ../n4.fasta -o test_cuttlefish2

Please use `--ref` for FASTA inputs and `--read` for FASTQ!

Regards.

**Comment by rlorigro** [comment]
I see, thanks. I hadn't thought that the implementations would be tied to file type.
