### ISSUE TITLE
Advice to do this for a large collection of genomes

### ISSUE THREAD

**Issue by rickbeeloo** [COMBINE-lab/cuttlefish#4]
We want to apply this to a large collection of genomes,  in the manuscript there is a section about this:

> On repositories with large databases containing many genome references, Cuttlefish can be applied
> very fast in an on-demand manner, as follows. First, one can build and store a set of hash functions, each
> one over some class of related genome references. This consists of the first two steps of the algorithm and is a
> one-time procedure, containing the bottleneck part of the algorithm. Then, whenever some set of references
> is to be compacted, the hash function of the appropriate class can be loaded into memory, and the algorithm
> then executes only the last two steps, which are quite fast. This works correctly because the sets of keys that
> these hash functions are built from are supersets of the sets of keys being used later for the compactions.
> Cuttlefish provides the option to save and load hash functions, making the scheme feasible

We now ran `cuttlefish` to generate a gfa2 for all genomes as a reference (`-l paths.txt` as mentioned in #3 ), however, we notice that opening and processing takes a considerable amount of time, so a step like this:
```
Opened reference 578 from /home/genome1.fna
Processing sequence 1, with length:	   5043468.
```
So I wonder:
1) What the in the paper mentioned approach would look like on the command line? 
2) Whether you have any other ideas when we apply this to large genome databases?

**Comment by jamshed-k** [comment]
Hi @rickbeeloo,

Thanks again for using Cuttlefish, and sorry for the delay in response. To answer the issues —

1. Yes, the first two phases of the pipeline, i.e. generating the _k_-mer set and constructing a hash function (specifically, an MPHF) over it can be done as a pre-processing step over (relevant) classes of genomes — and an appropriate hash function can be directly loaded into the memory later during the graph compaction, bypassing the first two steps. The currently working CLI for this (at [`develop`](https://github.com/COMBINE-lab/cuttlefish/tree/develop)) is —

   - Pre-processing step:

    ```bash
    # k-mer set generation
    kmc -k<k-mer_length> -fm -ci0 -t<thread-count> @<input_references_list> <output_set> <working_directory>

    # MPHF construction
    cuttlefish build -k <k-mer_length> -s <k-mer_set> -t <thread-count> -w <working_directory> --mph <MPHF>
    ```

   - Actual graph compaction:

    ```bash
    cuttlefish build -l <input_references_list> -k <k-mer_length> -s <k-mer_set> -t <thread-count> -w <working_directory> -o <output_file> -f <output_format> --mph <MPHF>
    ```

    The first step builds and saves the hash function at the path `MPHF` (note that, neither any input reference nor an output argument is provided, as we need only the hash function), and the later step directly loads it from there and resumes from the third step of the pipleline.

    Please note that, if you are compacting the graph for a reference set `R = {r_1, r_2, ..., r_n}` and for such using an MPHF `h` that was built over the set `K` of _k_-mers, then it must be maintained that each distinct  _k_-mer in `R` is present in `K`. The easiest way to ensure this is — if `h` was constructed for the reference set `S = {s_1, s_2, ...}`, then `R` must be a subset of `S`.

2. As you mentioned —
    > opening and processing takes a considerable amount of time

    The processing of the references take place both at the third (states-computation) and the fourth (output) step; but at the GFA output process, a considerable amount of disk-write is involved — which you may have already noticed from the output file sizes. This affects the timing-performance of the outputting-task non-trivially.

    A speedup can be achieved by using a _reduced_ format from GFA. Specifically, the links / edges in the GFA output may be considered redundant for this particular use case, i.e. for the GFA representation of the compacted de Bruijn graph. This is because the output includes a path-tiling for each individual sequence in the input references, i.e. an ordered list of the maximal unitig ids that completely tile that sequence. The edge-set can be completely inferred from these path-tilings, if required. And for many applications, only the path-tilings of the input sequences are relevant. This reduced format effectively removes more than 50% of the disk-writes. I had plans to include a custom option to have such a _GFA-reduced_ output format (i.e. skipping the edges). Do you think this format will be suitable for your purposes?

Let us know if these help!

**Comment by jamshed-k** [comment]
Hi,

Just as an update, we now have the faster to write and (much) more space-efficient [GFA-reduced](https://github.com/COMBINE-lab/cuttlefish/tree/develop#io-formats) output format.

**Comment by rickbeeloo** [comment]
Hi @jamshed-k, sorry for the late response, I'm back at the graphs again :) The reduced format looks promising! I immediately gonna check how fast this is for our enormous genome collection!

**Comment by rickbeeloo** [comment]
It worked amazing (and fast) for thousands of genomes!
