### ISSUE TITLE
Incorrect link between node and contigs?

### ISSUE THREAD

**Issue by rickbeeloo** [COMBINE-lab/cuttlefish#6]
I noticed this in our very big graph so I tried it with 5 genomes:

**Get the genomes from my github**
```
git clone https://github.com/rickbeeloo/cuttle_data.git
cd cuttle_data
unzip genomes.zip
find . -type f -name '*.fna' > test_paths.txt
```

**Graph construction**
Build the k-mer db
`kmc -fm -ci0 -t5 @test_paths.txt test_graph .`

Running cuttlefish
`cuttlefish build test_paths.txt -l test_paths.txt -k 25 -s test_graph -t 10 -o cuttle_out -f 3 -w .`

**Select a node from the seg file**
Selected a random node from `cuttle_out.cf_seg` for example `9627838` and put it in a fasta `node.fasta`

> 	AACATATCATCATAATGAGATGGTTCAAAAATTTGATTAACAATTAATGGCTTCATATTTCTAACAATGTCATCTAAGTGATTTTCTAAAATTGGTGAAGCTGTTTTTAAGTTATTTAAAAATTCATCTAAATTTTTAAGTTTACTTTTTAAAACTTCAAGGCTTTTATCAATTTCGTCGACATTTATTCCCATAGCCTTTATCTTTATTTTCATTGTTACTTTGTATATTAAACTGCTTATTTCATAAATATGTCTCACAGCTGTTTCTACCGAATGTATAACTTCAAGAATGTAGTTTAATACTGGTTCAAAATAATTATTGTAAGCTTCTTGAACATAATCACTAATTTTGTTAACTGCATTATCAATATGGTTTTTTAAAATTGTCATTTTTCTAGTTAAATAATTAGAAGATTGTACTTGACCCGAAATCATATGTTCACCGCTATAATTAATAGATAAGTTTCCATCCATTACCGTTGCATCTTGATGAGACATTATATTTTTAATATCGGTTATCTGCTCTCCATATACATCATTTTGTTTTTTTACAAAATTTATATTATTATTCACAACATTTAAATGCTTCATCATTTCCTCTGTCACGCCATCTTCAAAATCATGATCTAAATTTTTAAACATTTCTTTAATTACGTTATCCAGTGAATCATGTAAACTTTCTATGCCACGTTGTAATTTTTTATCTAAATCTTCAAGCATTTCTTCAATAGTATTTAATTCAAAAATAAGGACTGCAACTGATGAAAATATGAATGCAATTCCAACAAGATTTTTTTTGACATTATCAATTGCGCTAAATGCATCCTTTTTCAAAGAAGTTAATTCCCTACTCATTCCTTCAAGGATATCAACTTCGACAATCTTTTTAAAATCTTGTTTAAGTTTATGTTTTCTTTCTCCAAAATTAGCATTTTCAACCTGTGAAATATTATAGCTCTCGTTCAAATAATTTACACAATCGGTTAACATATTACTTGTTTCACCAGTTACCAAATTACTTAATGCACTAAGATTTTCTAGATTTAATTTTATAGGAGTCCCTTTACCCGTTCTCGCTATTGAATCTCCTGTCCACACATTAATTGGAATTCTATCATCCATATTTATATCGATTTCAATAGTTTTTTTGACTTTTTTACCATTTTTAATCATAGTATCTTTAACTGATTTAATTTTATAAACTGCTAAATCCTTATAAGTATTATATCTTGGATTTAATTTTCTTTTATAACCTAAATGACTATTTACTAATCCATCCATCGTTGGCACACCAGTTTCTAAATTCACTCGTTTTCCTAGTGTCGGAGTGGCAAATGGATCCTGCAGCCAAGATAAAATATCAAACTTACTATGATAATTAATCATATTTTCAAAGTTTTGAGATTTGAAATTTTCCCATATTGACTTTGGTAACATGGCAGGGTTTGTAGAAACTATATTTTTATTCGGGTTAATCATCCCTTGGTGGTTAGCACTTGCTCCCCCTTGAGAATTGCCTCCATCAGACTTAATAGTTTTGTTTTTATACGTAGACGGATTTTTCTTATATTTCCTTATAAAATCAGAGCTTTTAAGTGTATCTGCATCTTTTAGTTTCTGTTCATACGATTTAATATAAGCATTATTTTGTTCTAATAAAGAAGTTGACTTATTTTTATCATTCATTAACTTTATATTTTCAATCCAATCATCAGCAACCTTCCCACGAAAAGGATTGTTGCTTCCGATACTCTTATTATTATTTGTACCTTGGAAGATAATAGCTTGTTGTCCTGTTAATTCATTATTGCTATTTACCAATTCAAAAACTTTTGCATCTGTACCACCAAAACTTTTAGAATTAGGATTGTCTGAATAATCTTCAATTAGTCTATATTTATTATTATTTACTCTAATTACATATCTTTTGTCCAAATCTTGATATGCCCAGTATCCACTTAATTCTGCTAAATCTCTATCATTAATTTTTTTCATGATTAAATACTCCTACTTCTATTGAATCTTTCTTACTGTAACTAGGTCTTGCTGAATTTATATATTTATCAGTAATTTGAAGAGAAACATTCAAATCATGAGGAATATTCTTTTTCTTTTTTAGCACTTCAGAAAAATCAATCATCTCGTCTATTGTATTATCTTTAGTGTAATTGTCTTTAGTGCTAAATAAAGTTGTAACAACATATGGACGAGATTTATCTTTAAGTTGTTTTTTTGAGTTTTTCATACCATCACTAAAAGTCTTGTCATCCTCTTTGATTAAGGGTTGAAAATACTTTTTATATTCATCTAAAGTATATGGAATTGCAGTCAAATAATAATATTCATTTCTAAAACCACTATTCTGCGTTTTCATAATTGCATTTTCTGTATAACCAGTATATTTATATTTACTTTTATATTCTTTCAAAACTTCTGTTAAACTATCCAACTCTTGCTTATGAGCTCGATATTCAAAGCCGCTCAACACTGTACCTACTAGAGTACTCATATCATCGCCTTTATC

**Look in what genome and on what contig this node should be present**
`nano search.py`, code below in it
```
with open('cuttle_out.cf_seq','r') as in_file:
    for line in in_file:
        acc, path = line.split('\t')     
        if '9627838-' in path:
            print(acc)
```

Which gives us: Reference:1_Sequence:FQMB01000001.
So it should be in `1280.11202.fna` on contig **FQMB01000001**.

**Check it**<br>
Let's search the sequence in `1280.11202.fna`:

```
makeblastdb -dbtype nucl -in 1280.11202.fna
blastn -db 1280.11202.fna -query node.fasta
```

Which gives us:
```
                                                                      Score        E
Sequences producing significant alignments:                          (Bits)     Value

FQMB01000003 Staphylococcus aureus strain 3688STDY6125055 genome ...  4665       0.0  

```

<h3>So a match with the contig FQMB01000003 **not** with FQMB01000001</h3>
(I checked this for the regular GFA too, and there the same happens)

----

I hope I miss something here.... cause otherwise, we would have to reconstruct our big graph :( Let me know if something is unclear!

**Comment by rickbeeloo** [comment]
Cuttlefish appears to only use the identifier of the first contig in the FASTA but still search all other contigs too?

**Comment by rickbeeloo** [comment]
<h3> ISSUE FOUND </h3>
I have been looking into this issue and found that newlines after each contig result in this problem, so:

**Works fine**:
```
>ref1
ATCGATCAGCT
>ref2
CTGATCGATGC
```

**Result in the above problem**:
```
>ref1
ATCGATCAGCT

>ref2
CTGATCGATGC
```

When I remove the newlines after each contig for `1280.11202.fna`, and re-run cuttlefish the output has all contigs:                                                                                   
```
Reference:1_Sequence:FQMB01000001       2484567- 2238953- 5919690+ 6134380- 2041894- 5194616+ 10207579+ 7500862- 3736662- 9783708- 15127505- 9541407- 10483578- 12670715+ 7490641+ 3372231- 3919049- 472132>
Reference:1_Sequence:FQMB01000002       5921658+ 11736253+ 5141009+ 6623300+ 2973916+ 13530580+ 14218152- 10076606- 14484004+ 13119865- 3305095+ 13832514- 4092086+ 13476823- 3357518- 14026091- 5288600+ 1>
Reference:1_Sequence:FQMB01000003       4092086+ 13476823- 3357518- 6762774- 9137168- 6886802- 15959151- 2790284+ 4039501- 8798446+ 12951407+ 9017599+ 12392034+ 486096+ 7683261+ 14898896+ 4395675+ 240043>
Reference:1_Sequence:FQMB01000004       2208191+ 2479753+ 15528356- 3218535+ 2075795- 7654398- 15953353- 9866879+ 11575543- 8836819+ 15953353- 6304692+ 4305146- 12246719+ 11575543- 10346280+ 4305146- 241>
Reference:1_Sequence:FQMB01000005       2238953- 6650429- 14566969+ 5546595- 4439554- 2038720- 15127505- 5094380- 10626019+ 7689178+ 10609906+ 8470741+ 12456842- 1680815- 15525449- 13795480- 7201842- 577>
Reference:1_Sequence:FQMB01000006       11183892- 13144786- 7672775+ 10501998- 1578485+ 49287+ 9971082- 1967487+ 10764606- 11142982+ 12566694- 13767587- 4253013- 3719104- 8807786- 6005645- 11103295+ 1390>
Reference:1_Sequence:FQMB01000007       9585786+ 1809545+ 15557002- 4134732- 12062169- 2484567- 2238953- 6650429- 10631745- 7848977+ 10448029+ 1209509+ 8521807+ 9936971+ 10067520+ 7907973+ 9729933+ 10448>
Reference:1_Sequence:FQMB01000008       2208191+ 14667805+ 15580325+ 6882092- 9801546+ 6313252+ 4439554- 2038720- 15127505- 9541407- 10483578- 12670715+ 7490641+ 3372231- 3919049- 4721322+ 1207152- 21773>
Reference:1_Sequence:FQMB01000009       49287+ 9971082- 1967487+ 10764606- 11142982+ 12566694- 11020069- 3622974+ 7173590- 4253013- 1684341- 1225652- 9786764+ 1383316+ 7269244- 958343- 14380241- 10732877>
Reference:1_Sequence:FQMB01000010       3357518- 6762774- 11297848- 9758685- 7282234+ 14525260+ 11721932- 11028392+ 5518108+ 12979435- 9392725- 2263961- 1368307+ 2687552+ 15767389- 6594158+ 11807979- 761>
Reference:1_Sequence:FQMB01000011       2208191+ 14667805+ 15580325+ 6882092- 12021263+ 5732497- 1262518- 5732497- 14726225+ 10605865- 9557738+ 13932593+ 6449464- 5856771- 1784073- 9117838- 3218535+ 2075>
Reference:1_Sequence:FQMB01000012       4092086+ 13476823- 3357518- 6762774- 9137168- 6886802- 12660739- 2977522- 9929439- 2095332- 653375- 2095332- 12978960- 5221650+ 3368181- 11968495- 7556111+ 5221650>
Reference:1_Sequence:FQMB01000013       2238953- 12056582- 374184+ 15051938- 14007624+ 2517366+ 4931312+ 10851680+ 10599185+ 14252252- 6361099+ 11240714- 1838180- 6395955+ 7626252- 15458276- 13239948- 22>
Reference:1_Sequence:FQMB01000014       3539497- 871412- 15305687- 9074554- 10239418+ 1268628- 10767653- 1061952+ 4848538- 7085644+ 3733239+ 10137224+ 2605140- 8846888+ 15573369+ 8567278+ 3431812- 153507>
Reference:1_Sequence:FQMB01000015       3539497- 871412- 15305687- 9074554- 10239418+ 6214525+ 464615- 13784516+ 724566- 13784516+ 13224528+ 15051938- 10875690- 14214678- 8971980+ 2399720- 3665171- 24306>
Reference:1_Sequence:FQMB01000016       15450417+ 6475788- 13495523+ 5261649- 12094343- 13537060+ 7500790+ 1294586+ 1403470- 10044232- 6069180- 922182+ 9034350+ 2138788- 14864501+ 3782001- 5883729+ 14197>
Reference:1_Sequence:FQMB01000017       13867027- 1562193- 3482448- 2208191+ 14667805+ 15580325+ 8801637+ 822251- 5794133+ 8682233- 5794133+ 7963622- 8807786- 6005437- 14807189- 2479753- 2208191-
Reference:1_Sequence:FQMB01000018       1809545+ 2650199- 475473- 12062169- 2484567- 2238953- 5919690+ 4713868+ 14973114+ 5974274- 5919690- 2238953+
Reference:1_Sequence:FQMB01000019       2238953- 6650429- 11174199- 329833- 10764986+ 12067162+ 15010584+ 11934813- 11774274- 329833- 10764986+ 15499122+ 11774274- 329833- 15188082+ 15010584+ 3177044+ 72>
Reference:1_Sequence:FQMB01000020       12094343- 13537060+ 7500790+ 10990603- 10165652+ 11188636- 7788900- 5241717+ 3781224- 13614479- 8021028- 4897910+ 14310043- 1336972+ 7241939- 356812- 13513394+ 152>
Reference:1_Sequence:FQMB01000021       842248+ 14351779+ 14522759- 1413831+ 9842267- 1145853- 8496211+ 2814220- 811447+ 4226524+ 5697119+ 16053379+ 7445914- 6856064+ 10924857+ 6676325+ 1360937- 8196031+>
Reference:1_Sequence:FQMB01000022       827536+ 13058980- 4127879+ 2657970-
Reference:1_Sequence:FQMB01000023       4226524+ 5697119+ 580943+ 7182825+ 13417973- 11111334- 5526142+ 13735562+ 7182825+ 13908508+ 10924857+ 6676325+ 1360937- 8196031+ 11813654- 7173572+ 5439422- 13006>
Reference:1_Sequence:FQMB01000024       811447+ 4226524+ 5697119+ 16053379+ 2030186- 7484518- 12366468- 14016993+ 1360937- 8196031+ 1972427+ 5439422- 13006935+ 14897433+ 9414491+ 6332510+
Reference:1_Sequence:FQMB01000025       12094343- 13537060+ 7500790+ 9366520- 5864313- 1580407- 1225652+ 1684341+ 4253013+ 7173590+ 3622974- 15892609+ 5276318+ 10764606+ 1967487- 9971082+ 49287- 1578485-
Reference:1_Sequence:FQMB01000026       3409407+ 11607161+ 11571952+ 15688302+ 4850866- 12662665+ 7341617+ 11049936+ 7601727- 6486822+
Reference:1_Sequence:FQMB01000027       5697119+ 580943+ 7182825+ 13417973- 3769857- 5526142+ 13880606+ 6856064+ 10924857+ 6676325+ 1360937- 8196031+ 11813654- 7173572+ 5439422- 13006935+
```

**Comment by jamshed-k** [comment]
Hi @rickbeeloo,

Yes, exactly. I was looking into the issue right now—our underlying parsing library, i.e. [kseq](https://github.com/lh3/seqtk/blob/master/kseq.h) from the [seqtk](https://github.com/lh3/seqtk) toolkit does not correctly parse files containing empty lines. Specifically, this while loop [here](https://github.com/COMBINE-lab/cuttlefish/blob/2c65b6fbfdbc64a69836938b491e06d30e02d495/include/kseq/kseq.h#L187) expects one of the following characters to end reading the current sequence: an EOF (End-of-Line), a new sequence (with `>`), or some meta-info (with `+` or `@`). The empty line satisfies none, so the reading of the current sequence proceeds on—consuming the entire reference file as one sequence (given that all the sequences / contigs are empty-line separated). And alongside, the sequence is named after the very first sequence present in the input file.

**Comment by jamshed-k** [comment]
We would also like to add that, the presence of empty lines in the FASTA format is not supported by [the NCBI FASTA specification](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=BlastHelp), which makes the _undefined_ behavior of the parser not unexpected.

On another note regading the large graph that you've mentioned — do you have the hash function files (optional cuttlefish-byproduct) for the (super) key-sets, as had been suggested previously in #4? If you do, then the graph reconstruction cost can be cut down largely.

**Comment by rickbeeloo** [comment]
Hey @jamshed-k , thanks for taking a look!

**Update Kseq.h - current seqtk version does not suffer this problem**
>  an EOF (End-of-Line), a new sequence (with >), or some meta-info (with + or @).

The `hseq.k` for cuttlefish is pretty outdated being last modified at 18AUG2011. The [issue about the empty lines](https://github.com/lh3/seqtk/issues/3) was raised before and fixed in[ this commit](https://github.com/lh3/seqtk/commit/771d60b8f774482a77d60dd8559d17bd487c56e8). Indeed when we look at the current `kseq.h` we see an [added line here](https://github.com/lh3/seqtk/blob/c91a6afd5d9fa51c5069315a3a89c3d4b246fc22/kseq.h#L195) to solve this. 


**Fasta format**
> We would also like to add that, the presence of empty lines in the FASTA format is not supported by the NCBI FASTA specification, which makes the undefined behavior of the parser not unexpected.

I see, that's interesting, we retrieve our genomes from the [PATRIC database](https://www.patricbrc.org/), one of the largest databases for bacterial genomes. We will communicate this with them too. 

**Hash function**

> On another note regading the large graph that you've mentioned — do you have the hash function files (optional cuttlefish-byproduct) for the (super) key-sets, as had been suggested previously

Unfortunately not... our graph already took up terabytes so we cleaned all other files. But we will keep them this time! hahah


Thanks again!

**Comment by rickbeeloo** [comment]
I added the line `if (c == '\n') continue; /* skip empty lines */ \`, and rebuild cuttlefish and now it works fine with the empty lines, so perhaps worth updating `kseq.h`

**Comment by jamshed-k** [comment]
Hello @rickbeeloo,

Thanks for pointing out the difference in the `kseq` versions. We've updated the library to its latest version.

As you mentioned, this should be working correctly for you now. Please let us know if there are any other problems you may have faced relevant to this, and if not, then please close the issue.

Regards!

**Comment by rickbeeloo** [comment]
Awesome! thanks @jamshed-k !
